services:
  nginx:
    image: nginx:latest
    container_name: bingo
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
